
VARIANT_EFFECTS = {"SPLICE_SITE_ACCEPTOR": "high",
                   "SPLICE_SITE_DONOR": "high",
                   "START_LOST": "high",
                   "EXON_DELETED": "high",
                   "FRAME_SHIFT": "high",
                   "STOP_GAINED": "high",
                   "STOP_LOST": "high",
                   "RARE_AMINO_ACID": "high",
                   "NON_SYNONYMOUS_CODING": "moderate",
                   "CODON_CHANGE": "moderate",
                   "CODON_INSERTION": "moderate",
                   "CODON_CHANGE_PLUS_CODON_INSERTION": "moderate",
                   "CODON_DELETION": "moderate",
                   "CODON_CHANGE_PLUS_CODON_DELETION": "moderate",
                   "UTR_5_DELETED": "moderate",
                   "UTR_3_DELETED": "moderate",
                   "SYNONYMOUS_START": "low",
                   "NON_SYNONYMOUS_START": "low",
                   "START_GAINED": "low",
                   "SYNONYMOUS_CODING": "low",
                   "SYNONYMOUS_STOP": "low",
                   "UTR_5_PRIME": "modifier",
                   "UTR_3_PRIME": "modifier",
                   "REGULATION": "modifier",
                   "UPSTREAM": "modifier",
                   "DOWNSTREAM": "modifier",
                   "GENE": "modifier",
                   "TRANSCRIPT": "modifier",
                   "EXON": "modifier",
                   "INTRON_CONSERVED": "modifier",
                   "INTRON": "modifier",
                   "INTRAGENIC": "modifier",
                   "INTERGENIC": "modifier",
                   "INTERGENIC_CONSERVED": "modifier",
                   "NONE": "modifier",
                   "CHROMOSOME": "modifier",
                   "CUSTOM": "modifier",
                   "CDS": "modifier"}

VARIANT_RANKS = {"high": 4, "moderate": 3, "low": 2, "modifier": 1}

VARIANT_SHORTNAMES = {"SPLICE_SITE_ACCEPTOR": "Splice",
                      "SPLICE_SITE_DONOR": "Splice",
                      "START_LOST": "Start Lost",
                      "EXON_DELETED": "Exon Lost",
                      "FRAME_SHIFT": "Frameshift",
                      "STOP_GAINED": "Stop Gain",
                      "STOP_LOST": "Stop Loss",
                      "RARE_AMINO_ACID": "Rare AA",
                      "NON_SYNONYMOUS_CODING": "Missense",
                      "CODON_CHANGE": "Codon Change",
                      "CODON_INSERTION": "Codon Ins",
                      "CODON_CHANGE_PLUS_CODON_INSERTION": "Codon complex",
                      "CODON_DELETION": "Codon Lost",
                      "CODON_CHANGE_PLUS_CODON_DELETION": "Codon complex",
                      "UTR_5_DELETED": "UTR-5 Loss",
                      "UTR_3_DELETED": "UTR-3 Loss",
                      "SYNONYMOUS_START": "Syn. Start",
                      "NON_SYNONYMOUS_START": "Nonsyn. Start",
                      "START_GAINED": "Start gain",
                      "SYNONYMOUS_CODING": "Synonymous",
                      "SYNONYMOUS_STOP": "Syn. Stop",
                      "UTR_5_PRIME": "UTR-5",
                      "UTR_3_PRIME": "UTR-3",
                      "REGULATION": "Regulation",
                      "UPSTREAM": "Upstream",
                      "DOWNSTREAM": "Downstream",
                      "GENE": "Gene",
                      "TRANSCRIPT": "Transcript",
                      "EXON": "Exon",
                      "INTRON_CONSERVED": "Intron",
                      "INTRON": "Intron",
                      "INTRAGENIC": "Intragenic",
                      "INTERGENIC": "Intragenic",
                      "INTERGENIC_CONSERVED": "Intragenic",
                      "NONE": "None",
                      "CHROMOSOME": "Chromosome",
                      "CUSTOM": "Other",
                      "CDS": "CDS"}
